name: Pipeline
on: [push, pull_request]

jobs:
  test:
    run-on: ubuntu-latest

  
    steps:
      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '13.12.0'