    steps:
      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install

      - name: Executar testes
        run: poetry run task test